name: NodeJS with Webpack

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload to S3 & invalidate cloudfront
        uses: reggionick/s3-deploy@v3
        with:
          folder: dist
          bucket: twilight-imperium-app
          bucket-region: us-east-2
          dist-id: EYWERI3UJNTY5
          invalidation: /*
          delete-removed: true
